//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.02.22 at 11:45:16 AM YEKT 
//


package converter.kpt.kpt;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dApartmentType.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="dApartmentType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="кв"/&gt;
 *     &lt;enumeration value="бокс"/&gt;
 *     &lt;enumeration value="к"/&gt;
 *     &lt;enumeration value="пом"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "dApartmentType", namespace = "urn://x-artefacts-rosreestr-ru/commons/directories/apartment/1.0.1")
@XmlEnum
public enum DApartmentType {


    /**
     * Квартира
     * 
     */
    @XmlEnumValue("\u043a\u0432")
    КВ("\u043a\u0432"),

    /**
     * Бокс
     * 
     */
    @XmlEnumValue("\u0431\u043e\u043a\u0441")
    БОКС("\u0431\u043e\u043a\u0441"),

    /**
     * Комната
     * 
     */
    @XmlEnumValue("\u043a")
    К("\u043a"),

    /**
     * Помещение
     * 
     */
    @XmlEnumValue("\u043f\u043e\u043c")
    ПОМ("\u043f\u043e\u043c");
    private final String value;

    DApartmentType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DApartmentType fromValue(String v) {
        for (DApartmentType c: DApartmentType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
