//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.02.22 at 11:45:16 AM YEKT 
//


package converter.kpt.kpt;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dLocationLevel1Type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="dLocationLevel1Type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="д"/&gt;
 *     &lt;enumeration value="ГСК"/&gt;
 *     &lt;enumeration value="казарма"/&gt;
 *     &lt;enumeration value="уч"/&gt;
 *     &lt;enumeration value="вл"/&gt;
 *     &lt;enumeration value="бокс"/&gt;
 *     &lt;enumeration value="в/ч"/&gt;
 *     &lt;enumeration value="сооружение"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "dLocationLevel1Type", namespace = "urn://x-artefacts-rosreestr-ru/commons/directories/location-level-1/1.0.1")
@XmlEnum
public enum DLocationLevel1Type {


    /**
     * Дом
     * 
     */
    @XmlEnumValue("\u0434")
    Д("\u0434"),

    /**
     * Гаражно-строительный кооператив
     * 
     */
    ГСК("\u0413\u0421\u041a"),

    /**
     * казарма
     * 
     */
    @XmlEnumValue("\u043a\u0430\u0437\u0430\u0440\u043c\u0430")
    КАЗАРМА("\u043a\u0430\u0437\u0430\u0440\u043c\u0430"),

    /**
     * Участок
     * 
     */
    @XmlEnumValue("\u0443\u0447")
    УЧ("\u0443\u0447"),

    /**
     * Владение
     * 
     */
    @XmlEnumValue("\u0432\u043b")
    ВЛ("\u0432\u043b"),

    /**
     * бокс
     * 
     */
    @XmlEnumValue("\u0431\u043e\u043a\u0441")
    БОКС("\u0431\u043e\u043a\u0441"),

    /**
     * военная часть
     * 
     */
    @XmlEnumValue("\u0432/\u0447")
    В_Ч("\u0432/\u0447"),

    /**
     * сооружение
     * 
     */
    @XmlEnumValue("\u0441\u043e\u043e\u0440\u0443\u0436\u0435\u043d\u0438\u0435")
    СООРУЖЕНИЕ("\u0441\u043e\u043e\u0440\u0443\u0436\u0435\u043d\u0438\u0435");
    private final String value;

    DLocationLevel1Type(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DLocationLevel1Type fromValue(String v) {
        for (DLocationLevel1Type c: DLocationLevel1Type.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
