//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.02.22 at 11:45:16 AM YEKT 
//


package converter.kpt.kpt;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dLocationLevel2Type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="dLocationLevel2Type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="корп"/&gt;
 *     &lt;enumeration value="д"/&gt;
 *     &lt;enumeration value="уч"/&gt;
 *     &lt;enumeration value="вл"/&gt;
 *     &lt;enumeration value="гараж"/&gt;
 *     &lt;enumeration value="бокс"/&gt;
 *     &lt;enumeration value="строение"/&gt;
 *     &lt;enumeration value="сооружение"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "dLocationLevel2Type", namespace = "urn://x-artefacts-rosreestr-ru/commons/directories/location-level-2/1.0.1")
@XmlEnum
public enum DLocationLevel2Type {


    /**
     * Корпус
     * 
     */
    @XmlEnumValue("Корпус")
    КОРП("Корпус"),

    /**
     * Дом
     * 
     */
    @XmlEnumValue("Дом")
    Д("Дом"),

    /**
     * Участок
     * 
     */
    @XmlEnumValue("Участок")
    УЧ("Участок"),

    /**
     * Владение
     * 
     */
    @XmlEnumValue("Владение")
    ВЛ("Владение"),

    /**
     * Гараж
     * 
     */
    @XmlEnumValue("Гараж")
    ГАРАЖ("Гараж"),

    /**
     * бокс
     * 
     */
    @XmlEnumValue("бокс")
    БОКС("бокс"),

    /**
     * строение
     * 
     */
    @XmlEnumValue("строение")
    СТРОЕНИЕ("строение"),

    /**
     * сооружение
     * 
     */
    @XmlEnumValue("сооружение")
    СООРУЖЕНИЕ("сооружение");
    private final String value;

    DLocationLevel2Type(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DLocationLevel2Type fromValue(String v) {
        for (DLocationLevel2Type c: DLocationLevel2Type.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
