//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.02.22 at 11:45:16 AM YEKT 
//


package converter.kpt.kpt;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dUrbanDistrict.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="dUrbanDistrict"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="р-н"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "dUrbanDistrict", namespace = "urn://x-artefacts-rosreestr-ru/commons/directories/urban-district/1.0.1")
@XmlEnum
public enum DUrbanDistrict {


    /**
     * район
     * 
     */
    @XmlEnumValue("\u0440-\u043d")
    Р_Н("\u0440-\u043d");
    private final String value;

    DUrbanDistrict(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DUrbanDistrict fromValue(String v) {
        for (DUrbanDistrict c: DUrbanDistrict.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
