//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.02.22 at 11:45:16 AM YEKT 
//


package converter.kpt.kpt;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.uriit.kptConverter.kpt package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AttachmentRef_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "AttachmentRef");
    private final static QName _PrimaryIdentityDocument_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "PrimaryIdentityDocument");
    private final static QName _IdentityDocument_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "IdentityDocument");
    private final static QName _PassportRF_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "PassportRF");
    private final static QName _ForeignPassport_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "ForeignPassport");
    private final static QName _ResidencePermitRF_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "ResidencePermitRF");
    private final static QName _InternationalPassportRF_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "InternationalPassportRF");
    private final static QName _MilitaryPassport_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "MilitaryPassport");
    private final static QName _SailorPassport_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "SailorPassport");
    private final static QName _SovietPassport_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "SovietPassport");
    private final static QName _BirthCertificate_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "BirthCertificate");
    private final static QName _DrivingLicenseRF_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "DrivingLicenseRF");
    private final static QName _ReleaseCertificate_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "ReleaseCertificate");
    private final static QName _PassportLossCertificate_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "PassportLossCertificate");
    private final static QName _Form9Certificate_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "Form9Certificate");
    private final static QName _TemporaryIdentityCardRF_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", "TemporaryIdentityCardRF");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.uriit.kptConverter.kpt
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link KPT }
     * 
     */
    public KPT createKPT() {
        return new KPT();
    }

    /**
     * Create an instance of {@link TElementsConstruct }
     * 
     */
    public TElementsConstruct createTElementsConstruct() {
        return new TElementsConstruct();
    }

    /**
     * Create an instance of {@link TSpelementUnitLandKVOut }
     * 
     */
    public TSpelementUnitLandKVOut createTSpelementUnitLandKVOut() {
        return new TSpelementUnitLandKVOut();
    }

    /**
     * Create an instance of {@link TSpelementUnitLandOut }
     * 
     */
    public TSpelementUnitLandOut createTSpelementUnitLandOut() {
        return new TSpelementUnitLandOut();
    }

    /**
     * Create an instance of {@link TBorderLand }
     * 
     */
    public TBorderLand createTBorderLand() {
        return new TBorderLand();
    }

    /**
     * Create an instance of {@link TBorderLand.Edge }
     * 
     */
    public TBorderLand.Edge createTBorderLandEdge() {
        return new TBorderLand.Edge();
    }

    /**
     * Create an instance of {@link TEntitySpatialBordersLand }
     * 
     */
    public TEntitySpatialBordersLand createTEntitySpatialBordersLand() {
        return new TEntitySpatialBordersLand();
    }

    /**
     * Create an instance of {@link TSpelementUnitLandInp }
     * 
     */
    public TSpelementUnitLandInp createTSpelementUnitLandInp() {
        return new TSpelementUnitLandInp();
    }

    /**
     * Create an instance of {@link TSpelementUnitOKSOut }
     * 
     */
    public TSpelementUnitOKSOut createTSpelementUnitOKSOut() {
        return new TSpelementUnitOKSOut();
    }

    /**
     * Create an instance of {@link TEntitySpatialOKSOut }
     * 
     */
    public TEntitySpatialOKSOut createTEntitySpatialOKSOut() {
        return new TEntitySpatialOKSOut();
    }

    /**
     * Create an instance of {@link TEntitySpatialBordersZUOut }
     * 
     */
    public TEntitySpatialBordersZUOut createTEntitySpatialBordersZUOut() {
        return new TEntitySpatialBordersZUOut();
    }

    /**
     * Create an instance of {@link TEntitySpatialBordersZUOut.Borders }
     * 
     */
    public TEntitySpatialBordersZUOut.Borders createTEntitySpatialBordersZUOutBorders() {
        return new TEntitySpatialBordersZUOut.Borders();
    }

    /**
     * Create an instance of {@link TEntitySpatialBordersZUOut.Borders.Border }
     * 
     */
    public TEntitySpatialBordersZUOut.Borders.Border createTEntitySpatialBordersZUOutBordersBorder() {
        return new TEntitySpatialBordersZUOut.Borders.Border();
    }

    /**
     * Create an instance of {@link TSpelementUnitZUOut }
     * 
     */
    public TSpelementUnitZUOut createTSpelementUnitZUOut() {
        return new TSpelementUnitZUOut();
    }

    /**
     * Create an instance of {@link TSpelementUnitOKSInp }
     * 
     */
    public TSpelementUnitOKSInp createTSpelementUnitOKSInp() {
        return new TSpelementUnitOKSInp();
    }

    /**
     * Create an instance of {@link TEntitySpatialOKSInp }
     * 
     */
    public TEntitySpatialOKSInp createTEntitySpatialOKSInp() {
        return new TEntitySpatialOKSInp();
    }

    /**
     * Create an instance of {@link TBordersInp }
     * 
     */
    public TBordersInp createTBordersInp() {
        return new TBordersInp();
    }

    /**
     * Create an instance of {@link TSpelementUnitZUInp }
     * 
     */
    public TSpelementUnitZUInp createTSpelementUnitZUInp() {
        return new TSpelementUnitZUInp();
    }

    /**
     * Create an instance of {@link TObjectsRealty }
     * 
     */
    public TObjectsRealty createTObjectsRealty() {
        return new TObjectsRealty();
    }

    /**
     * Create an instance of {@link TObjectsRealty.ObjectRealty }
     * 
     */
    public TObjectsRealty.ObjectRealty createTObjectsRealtyObjectRealty() {
        return new TObjectsRealty.ObjectRealty();
    }

    /**
     * Create an instance of {@link TOMSPoints }
     * 
     */
    public TOMSPoints createTOMSPoints() {
        return new TOMSPoints();
    }

    /**
     * Create an instance of {@link TParcel }
     * 
     */
    public TParcel createTParcel() {
        return new TParcel();
    }

    /**
     * Create an instance of {@link TCadastralBlock }
     * 
     */
    public TCadastralBlock createTCadastralBlock() {
        return new TCadastralBlock();
    }

    /**
     * Create an instance of {@link TCadastralBlock.Zones }
     * 
     */
    public TCadastralBlock.Zones createTCadastralBlockZones() {
        return new TCadastralBlock.Zones();
    }

    /**
     * Create an instance of {@link TCadastralBlock.Zones.Zone }
     * 
     */
    public TCadastralBlock.Zones.Zone createTCadastralBlockZonesZone() {
        return new TCadastralBlock.Zones.Zone();
    }

    /**
     * Create an instance of {@link TCadastralBlock.Bounds }
     * 
     */
    public TCadastralBlock.Bounds createTCadastralBlockBounds() {
        return new TCadastralBlock.Bounds();
    }

    /**
     * Create an instance of {@link TCadastralBlock.Bounds.Bound }
     * 
     */
    public TCadastralBlock.Bounds.Bound createTCadastralBlockBoundsBound() {
        return new TCadastralBlock.Bounds.Bound();
    }

    /**
     * Create an instance of {@link TCadastralBlock.Bounds.Bound.Boundaries }
     * 
     */
    public TCadastralBlock.Bounds.Bound.Boundaries createTCadastralBlockBoundsBoundBoundaries() {
        return new TCadastralBlock.Bounds.Bound.Boundaries();
    }

    /**
     * Create an instance of {@link TCadastralBlock.SpatialData }
     * 
     */
    public TCadastralBlock.SpatialData createTCadastralBlockSpatialData() {
        return new TCadastralBlock.SpatialData();
    }

    /**
     * Create an instance of {@link TCertificationDoc }
     * 
     */
    public TCertificationDoc createTCertificationDoc() {
        return new TCertificationDoc();
    }

    /**
     * Create an instance of {@link KPT.CadastralBlocks }
     * 
     */
    public KPT.CadastralBlocks createKPTCadastralBlocks() {
        return new KPT.CadastralBlocks();
    }

    /**
     * Create an instance of {@link TContour }
     * 
     */
    public TContour createTContour() {
        return new TContour();
    }

    /**
     * Create an instance of {@link TLandUnit }
     * 
     */
    public TLandUnit createTLandUnit() {
        return new TLandUnit();
    }

    /**
     * Create an instance of {@link TUtilization }
     * 
     */
    public TUtilization createTUtilization() {
        return new TUtilization();
    }

    /**
     * Create an instance of {@link TAreaOut }
     * 
     */
    public TAreaOut createTAreaOut() {
        return new TAreaOut();
    }

    /**
     * Create an instance of {@link TAreaCadastralBlock }
     * 
     */
    public TAreaCadastralBlock createTAreaCadastralBlock() {
        return new TAreaCadastralBlock();
    }

    /**
     * Create an instance of {@link TName }
     * 
     */
    public TName createTName() {
        return new TName();
    }

    /**
     * Create an instance of {@link TBuilding }
     * 
     */
    public TBuilding createTBuilding() {
        return new TBuilding();
    }

    /**
     * Create an instance of {@link TConstruction }
     * 
     */
    public TConstruction createTConstruction() {
        return new TConstruction();
    }

    /**
     * Create an instance of {@link TUncompleted }
     * 
     */
    public TUncompleted createTUncompleted() {
        return new TUncompleted();
    }

    /**
     * Create an instance of {@link TConditionalPartLinear }
     * 
     */
    public TConditionalPartLinear createTConditionalPartLinear() {
        return new TConditionalPartLinear();
    }

    /**
     * Create an instance of {@link TTerritorialZone }
     * 
     */
    public TTerritorialZone createTTerritorialZone() {
        return new TTerritorialZone();
    }

    /**
     * Create an instance of {@link TSpecialZones }
     * 
     */
    public TSpecialZones createTSpecialZones() {
        return new TSpecialZones();
    }

    /**
     * Create an instance of {@link TPermittedUses }
     * 
     */
    public TPermittedUses createTPermittedUses() {
        return new TPermittedUses();
    }

    /**
     * Create an instance of {@link TPermittedUseAll }
     * 
     */
    public TPermittedUseAll createTPermittedUseAll() {
        return new TPermittedUseAll();
    }

    /**
     * Create an instance of {@link TPermittedUse }
     * 
     */
    public TPermittedUse createTPermittedUse() {
        return new TPermittedUse();
    }

    /**
     * Create an instance of {@link TLocation }
     * 
     */
    public TLocation createTLocation() {
        return new TLocation();
    }

    /**
     * Create an instance of {@link TElaborationLocation }
     * 
     */
    public TElaborationLocation createTElaborationLocation() {
        return new TElaborationLocation();
    }

    /**
     * Create an instance of {@link AttachmentRefType }
     * 
     */
    public AttachmentRefType createAttachmentRefType() {
        return new AttachmentRefType();
    }

    /**
     * Create an instance of {@link PrimaryIdentityDocumentType }
     * 
     */
    public PrimaryIdentityDocumentType createPrimaryIdentityDocumentType() {
        return new PrimaryIdentityDocumentType();
    }

    /**
     * Create an instance of {@link AnyIdentityDocumentType }
     * 
     */
    public AnyIdentityDocumentType createAnyIdentityDocumentType() {
        return new AnyIdentityDocumentType();
    }

    /**
     * Create an instance of {@link PassportRFType }
     * 
     */
    public PassportRFType createPassportRFType() {
        return new PassportRFType();
    }

    /**
     * Create an instance of {@link NotRestrictedDocumentType }
     * 
     */
    public NotRestrictedDocumentType createNotRestrictedDocumentType() {
        return new NotRestrictedDocumentType();
    }

    /**
     * Create an instance of {@link InternationalPassportRFType }
     * 
     */
    public InternationalPassportRFType createInternationalPassportRFType() {
        return new InternationalPassportRFType();
    }

    /**
     * Create an instance of {@link MilitaryPassportDocumentType }
     * 
     */
    public MilitaryPassportDocumentType createMilitaryPassportDocumentType() {
        return new MilitaryPassportDocumentType();
    }

    /**
     * Create an instance of {@link SovietPassportType }
     * 
     */
    public SovietPassportType createSovietPassportType() {
        return new SovietPassportType();
    }

    /**
     * Create an instance of {@link DrivingLicenseRFType }
     * 
     */
    public DrivingLicenseRFType createDrivingLicenseRFType() {
        return new DrivingLicenseRFType();
    }

    /**
     * Create an instance of {@link TAddressOut }
     * 
     */
    public TAddressOut createTAddressOut() {
        return new TAddressOut();
    }

    /**
     * Create an instance of {@link TNameAddr }
     * 
     */
    public TNameAddr createTNameAddr() {
        return new TNameAddr();
    }

    /**
     * Create an instance of {@link TUrbanDistrict }
     * 
     */
    public TUrbanDistrict createTUrbanDistrict() {
        return new TUrbanDistrict();
    }

    /**
     * Create an instance of {@link TSovietVillage }
     * 
     */
    public TSovietVillage createTSovietVillage() {
        return new TSovietVillage();
    }

    /**
     * Create an instance of {@link TLevel1 }
     * 
     */
    public TLevel1 createTLevel1() {
        return new TLevel1();
    }

    /**
     * Create an instance of {@link TLevel2 }
     * 
     */
    public TLevel2 createTLevel2() {
        return new TLevel2();
    }

    /**
     * Create an instance of {@link TLevel3 }
     * 
     */
    public TLevel3 createTLevel3() {
        return new TLevel3();
    }

    /**
     * Create an instance of {@link TApartment }
     * 
     */
    public TApartment createTApartment() {
        return new TApartment();
    }

    /**
     * Create an instance of {@link TCadastralCost }
     * 
     */
    public TCadastralCost createTCadastralCost() {
        return new TCadastralCost();
    }

    /**
     * Create an instance of {@link TCadastralCostExt }
     * 
     */
    public TCadastralCostExt createTCadastralCostExt() {
        return new TCadastralCostExt();
    }

    /**
     * Create an instance of {@link TCoordSystems }
     * 
     */
    public TCoordSystems createTCoordSystems() {
        return new TCoordSystems();
    }

    /**
     * Create an instance of {@link TCoordSystem }
     * 
     */
    public TCoordSystem createTCoordSystem() {
        return new TCoordSystem();
    }

    /**
     * Create an instance of {@link TOrdinateInp }
     * 
     */
    public TOrdinateInp createTOrdinateInp() {
        return new TOrdinateInp();
    }

    /**
     * Create an instance of {@link TOrdinateOut }
     * 
     */
    public TOrdinateOut createTOrdinateOut() {
        return new TOrdinateOut();
    }

    /**
     * Create an instance of {@link TOrdinateXY }
     * 
     */
    public TOrdinateXY createTOrdinateXY() {
        return new TOrdinateXY();
    }

    /**
     * Create an instance of {@link TBorder }
     * 
     */
    public TBorder createTBorder() {
        return new TBorder();
    }

    /**
     * Create an instance of {@link TLength }
     * 
     */
    public TLength createTLength() {
        return new TLength();
    }

    /**
     * Create an instance of {@link TDirectionAngle }
     * 
     */
    public TDirectionAngle createTDirectionAngle() {
        return new TDirectionAngle();
    }

    /**
     * Create an instance of {@link TBordersAgreement }
     * 
     */
    public TBordersAgreement createTBordersAgreement() {
        return new TBordersAgreement();
    }

    /**
     * Create an instance of {@link TBorderAgreement }
     * 
     */
    public TBorderAgreement createTBorderAgreement() {
        return new TBorderAgreement();
    }

    /**
     * Create an instance of {@link TEntitySpatialZUInp }
     * 
     */
    public TEntitySpatialZUInp createTEntitySpatialZUInp() {
        return new TEntitySpatialZUInp();
    }

    /**
     * Create an instance of {@link TSpatialElementZUInp }
     * 
     */
    public TSpatialElementZUInp createTSpatialElementZUInp() {
        return new TSpatialElementZUInp();
    }

    /**
     * Create an instance of {@link TEntitySpatialBordersZUInp }
     * 
     */
    public TEntitySpatialBordersZUInp createTEntitySpatialBordersZUInp() {
        return new TEntitySpatialBordersZUInp();
    }

    /**
     * Create an instance of {@link TSpatialElementOKSInp }
     * 
     */
    public TSpatialElementOKSInp createTSpatialElementOKSInp() {
        return new TSpatialElementOKSInp();
    }

    /**
     * Create an instance of {@link TEntitySpatialZUOut }
     * 
     */
    public TEntitySpatialZUOut createTEntitySpatialZUOut() {
        return new TEntitySpatialZUOut();
    }

    /**
     * Create an instance of {@link TSpatialElementZUOut }
     * 
     */
    public TSpatialElementZUOut createTSpatialElementZUOut() {
        return new TSpatialElementZUOut();
    }

    /**
     * Create an instance of {@link TCadastralNumbersOut }
     * 
     */
    public TCadastralNumbersOut createTCadastralNumbersOut() {
        return new TCadastralNumbersOut();
    }

    /**
     * Create an instance of {@link TSpatialElementOKSOut }
     * 
     */
    public TSpatialElementOKSOut createTSpatialElementOKSOut() {
        return new TSpatialElementOKSOut();
    }

    /**
     * Create an instance of {@link TEntitySpatialLandInp }
     * 
     */
    public TEntitySpatialLandInp createTEntitySpatialLandInp() {
        return new TEntitySpatialLandInp();
    }

    /**
     * Create an instance of {@link TSpatialElementLandInp }
     * 
     */
    public TSpatialElementLandInp createTSpatialElementLandInp() {
        return new TSpatialElementLandInp();
    }

    /**
     * Create an instance of {@link TEntitySpatialLandOut }
     * 
     */
    public TEntitySpatialLandOut createTEntitySpatialLandOut() {
        return new TEntitySpatialLandOut();
    }

    /**
     * Create an instance of {@link TSpatialElementLandOut }
     * 
     */
    public TSpatialElementLandOut createTSpatialElementLandOut() {
        return new TSpatialElementLandOut();
    }

    /**
     * Create an instance of {@link TEntitySpatialLandKVOut }
     * 
     */
    public TEntitySpatialLandKVOut createTEntitySpatialLandKVOut() {
        return new TEntitySpatialLandKVOut();
    }

    /**
     * Create an instance of {@link TSpatialElementLandKVOut }
     * 
     */
    public TSpatialElementLandKVOut createTSpatialElementLandKVOut() {
        return new TSpatialElementLandKVOut();
    }

    /**
     * Create an instance of {@link TEntitySpatial }
     * 
     */
    public TEntitySpatial createTEntitySpatial() {
        return new TEntitySpatial();
    }

    /**
     * Create an instance of {@link TSpatialElement }
     * 
     */
    public TSpatialElement createTSpatialElement() {
        return new TSpatialElement();
    }

    /**
     * Create an instance of {@link TSpelementUnit }
     * 
     */
    public TSpelementUnit createTSpelementUnit() {
        return new TSpelementUnit();
    }

    /**
     * Create an instance of {@link TOrdinate }
     * 
     */
    public TOrdinate createTOrdinate() {
        return new TOrdinate();
    }

    /**
     * Create an instance of {@link TExploitationChar }
     * 
     */
    public TExploitationChar createTExploitationChar() {
        return new TExploitationChar();
    }

    /**
     * Create an instance of {@link TFloors }
     * 
     */
    public TFloors createTFloors() {
        return new TFloors();
    }

    /**
     * Create an instance of {@link TKeyParameters }
     * 
     */
    public TKeyParameters createTKeyParameters() {
        return new TKeyParameters();
    }

    /**
     * Create an instance of {@link TKeyParameter }
     * 
     */
    public TKeyParameter createTKeyParameter() {
        return new TKeyParameter();
    }

    /**
     * Create an instance of {@link TKeyParametersSubObject }
     * 
     */
    public TKeyParametersSubObject createTKeyParametersSubObject() {
        return new TKeyParametersSubObject();
    }

    /**
     * Create an instance of {@link TKeyParameterSubObject }
     * 
     */
    public TKeyParameterSubObject createTKeyParameterSubObject() {
        return new TKeyParameterSubObject();
    }

    /**
     * Create an instance of {@link TDocumentWithoutAppliedFile }
     * 
     */
    public TDocumentWithoutAppliedFile createTDocumentWithoutAppliedFile() {
        return new TDocumentWithoutAppliedFile();
    }

    /**
     * Create an instance of {@link TElementsConstruct.Material }
     * 
     */
    public TElementsConstruct.Material createTElementsConstructMaterial() {
        return new TElementsConstruct.Material();
    }

    /**
     * Create an instance of {@link TSpelementUnitLandKVOut.Ordinate }
     * 
     */
    public TSpelementUnitLandKVOut.Ordinate createTSpelementUnitLandKVOutOrdinate() {
        return new TSpelementUnitLandKVOut.Ordinate();
    }

    /**
     * Create an instance of {@link TSpelementUnitLandOut.Ordinate }
     * 
     */
    public TSpelementUnitLandOut.Ordinate createTSpelementUnitLandOutOrdinate() {
        return new TSpelementUnitLandOut.Ordinate();
    }

    /**
     * Create an instance of {@link TBorderLand.Edge.Neighbours }
     * 
     */
    public TBorderLand.Edge.Neighbours createTBorderLandEdgeNeighbours() {
        return new TBorderLand.Edge.Neighbours();
    }

    /**
     * Create an instance of {@link TEntitySpatialBordersLand.Borders }
     * 
     */
    public TEntitySpatialBordersLand.Borders createTEntitySpatialBordersLandBorders() {
        return new TEntitySpatialBordersLand.Borders();
    }

    /**
     * Create an instance of {@link TSpelementUnitLandInp.Ordinate }
     * 
     */
    public TSpelementUnitLandInp.Ordinate createTSpelementUnitLandInpOrdinate() {
        return new TSpelementUnitLandInp.Ordinate();
    }

    /**
     * Create an instance of {@link TSpelementUnitOKSOut.Ordinate }
     * 
     */
    public TSpelementUnitOKSOut.Ordinate createTSpelementUnitOKSOutOrdinate() {
        return new TSpelementUnitOKSOut.Ordinate();
    }

    /**
     * Create an instance of {@link TEntitySpatialOKSOut.SpatialElement }
     * 
     */
    public TEntitySpatialOKSOut.SpatialElement createTEntitySpatialOKSOutSpatialElement() {
        return new TEntitySpatialOKSOut.SpatialElement();
    }

    /**
     * Create an instance of {@link TEntitySpatialBordersZUOut.Borders.Border.Edge }
     * 
     */
    public TEntitySpatialBordersZUOut.Borders.Border.Edge createTEntitySpatialBordersZUOutBordersBorderEdge() {
        return new TEntitySpatialBordersZUOut.Borders.Border.Edge();
    }

    /**
     * Create an instance of {@link TSpelementUnitZUOut.Ordinate }
     * 
     */
    public TSpelementUnitZUOut.Ordinate createTSpelementUnitZUOutOrdinate() {
        return new TSpelementUnitZUOut.Ordinate();
    }

    /**
     * Create an instance of {@link TSpelementUnitOKSInp.Ordinate }
     * 
     */
    public TSpelementUnitOKSInp.Ordinate createTSpelementUnitOKSInpOrdinate() {
        return new TSpelementUnitOKSInp.Ordinate();
    }

    /**
     * Create an instance of {@link TEntitySpatialOKSInp.SpatialElement }
     * 
     */
    public TEntitySpatialOKSInp.SpatialElement createTEntitySpatialOKSInpSpatialElement() {
        return new TEntitySpatialOKSInp.SpatialElement();
    }

    /**
     * Create an instance of {@link TBordersInp.Border }
     * 
     */
    public TBordersInp.Border createTBordersInpBorder() {
        return new TBordersInp.Border();
    }

    /**
     * Create an instance of {@link TSpelementUnitZUInp.Ordinate }
     * 
     */
    public TSpelementUnitZUInp.Ordinate createTSpelementUnitZUInpOrdinate() {
        return new TSpelementUnitZUInp.Ordinate();
    }

    /**
     * Create an instance of {@link TObjectsRealty.ObjectRealty.Construction }
     * 
     */
    public TObjectsRealty.ObjectRealty.Construction createTObjectsRealtyObjectRealtyConstruction() {
        return new TObjectsRealty.ObjectRealty.Construction();
    }

    /**
     * Create an instance of {@link TOMSPoints.OMSPoint }
     * 
     */
    public TOMSPoints.OMSPoint createTOMSPointsOMSPoint() {
        return new TOMSPoints.OMSPoint();
    }

    /**
     * Create an instance of {@link TParcel.Contours }
     * 
     */
    public TParcel.Contours createTParcelContours() {
        return new TParcel.Contours();
    }

    /**
     * Create an instance of {@link TCadastralBlock.Parcels }
     * 
     */
    public TCadastralBlock.Parcels createTCadastralBlockParcels() {
        return new TCadastralBlock.Parcels();
    }

    /**
     * Create an instance of {@link TCadastralBlock.Zones.Zone.Documents }
     * 
     */
    public TCadastralBlock.Zones.Zone.Documents createTCadastralBlockZonesZoneDocuments() {
        return new TCadastralBlock.Zones.Zone.Documents();
    }

    /**
     * Create an instance of {@link TCadastralBlock.Bounds.Bound.Documents }
     * 
     */
    public TCadastralBlock.Bounds.Bound.Documents createTCadastralBlockBoundsBoundDocuments() {
        return new TCadastralBlock.Bounds.Bound.Documents();
    }

    /**
     * Create an instance of {@link TCadastralBlock.Bounds.Bound.SubjectsBoundary }
     * 
     */
    public TCadastralBlock.Bounds.Bound.SubjectsBoundary createTCadastralBlockBoundsBoundSubjectsBoundary() {
        return new TCadastralBlock.Bounds.Bound.SubjectsBoundary();
    }

    /**
     * Create an instance of {@link TCadastralBlock.Bounds.Bound.Boundaries.Boundary }
     * 
     */
    public TCadastralBlock.Bounds.Bound.Boundaries.Boundary createTCadastralBlockBoundsBoundBoundariesBoundary() {
        return new TCadastralBlock.Bounds.Bound.Boundaries.Boundary();
    }

    /**
     * Create an instance of {@link TCadastralBlock.SpatialData.Documents }
     * 
     */
    public TCadastralBlock.SpatialData.Documents createTCadastralBlockSpatialDataDocuments() {
        return new TCadastralBlock.SpatialData.Documents();
    }

    /**
     * Create an instance of {@link TCertificationDoc.Official }
     * 
     */
    public TCertificationDoc.Official createTCertificationDocOfficial() {
        return new TCertificationDoc.Official();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttachmentRefType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AttachmentRefType }{@code >}
     */
    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", name = "AttachmentRef")
    public JAXBElement<AttachmentRefType> createAttachmentRef(AttachmentRefType value) {
        return new JAXBElement<AttachmentRefType>(_AttachmentRef_QNAME, AttachmentRefType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrimaryIdentityDocumentType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PrimaryIdentityDocumentType }{@code >}
     */
    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", name = "PrimaryIdentityDocument")
    public JAXBElement<PrimaryIdentityDocumentType> createPrimaryIdentityDocument(PrimaryIdentityDocumentType value) {
        return new JAXBElement<PrimaryIdentityDocumentType>(_PrimaryIdentityDocument_QNAME, PrimaryIdentityDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnyIdentityDocumentType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AnyIdentityDocumentType }{@code >}
     */
    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", name = "IdentityDocument")
    public JAXBElement<AnyIdentityDocumentType> createIdentityDocument(AnyIdentityDocumentType value) {
        return new JAXBElement<AnyIdentityDocumentType>(_IdentityDocument_QNAME, AnyIdentityDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PassportRFType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PassportRFType }{@code >}
     */
    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", name = "PassportRF")
    public JAXBElement<PassportRFType> createPassportRF(PassportRFType value) {
        return new JAXBElement<PassportRFType>(_PassportRF_QNAME, PassportRFType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotRestrictedDocumentType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NotRestrictedDocumentType }{@code >}
     */
    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", name = "ForeignPassport")
    public JAXBElement<NotRestrictedDocumentType> createForeignPassport(NotRestrictedDocumentType value) {
        return new JAXBElement<NotRestrictedDocumentType>(_ForeignPassport_QNAME, NotRestrictedDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InternationalPassportRFType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InternationalPassportRFType }{@code >}
     */
    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", name = "ResidencePermitRF")
    public JAXBElement<InternationalPassportRFType> createResidencePermitRF(InternationalPassportRFType value) {
        return new JAXBElement<InternationalPassportRFType>(_ResidencePermitRF_QNAME, InternationalPassportRFType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InternationalPassportRFType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InternationalPassportRFType }{@code >}
     */
    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", name = "InternationalPassportRF")
    public JAXBElement<InternationalPassportRFType> createInternationalPassportRF(InternationalPassportRFType value) {
        return new JAXBElement<InternationalPassportRFType>(_InternationalPassportRF_QNAME, InternationalPassportRFType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MilitaryPassportDocumentType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link MilitaryPassportDocumentType }{@code >}
     */
    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", name = "MilitaryPassport")
    public JAXBElement<MilitaryPassportDocumentType> createMilitaryPassport(MilitaryPassportDocumentType value) {
        return new JAXBElement<MilitaryPassportDocumentType>(_MilitaryPassport_QNAME, MilitaryPassportDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MilitaryPassportDocumentType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link MilitaryPassportDocumentType }{@code >}
     */
    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", name = "SailorPassport")
    public JAXBElement<MilitaryPassportDocumentType> createSailorPassport(MilitaryPassportDocumentType value) {
        return new JAXBElement<MilitaryPassportDocumentType>(_SailorPassport_QNAME, MilitaryPassportDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SovietPassportType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SovietPassportType }{@code >}
     */
    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", name = "SovietPassport")
    public JAXBElement<SovietPassportType> createSovietPassport(SovietPassportType value) {
        return new JAXBElement<SovietPassportType>(_SovietPassport_QNAME, SovietPassportType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SovietPassportType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SovietPassportType }{@code >}
     */
    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", name = "BirthCertificate")
    public JAXBElement<SovietPassportType> createBirthCertificate(SovietPassportType value) {
        return new JAXBElement<SovietPassportType>(_BirthCertificate_QNAME, SovietPassportType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DrivingLicenseRFType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DrivingLicenseRFType }{@code >}
     */
    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", name = "DrivingLicenseRF")
    public JAXBElement<DrivingLicenseRFType> createDrivingLicenseRF(DrivingLicenseRFType value) {
        return new JAXBElement<DrivingLicenseRFType>(_DrivingLicenseRF_QNAME, DrivingLicenseRFType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotRestrictedDocumentType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NotRestrictedDocumentType }{@code >}
     */
    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", name = "ReleaseCertificate")
    public JAXBElement<NotRestrictedDocumentType> createReleaseCertificate(NotRestrictedDocumentType value) {
        return new JAXBElement<NotRestrictedDocumentType>(_ReleaseCertificate_QNAME, NotRestrictedDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotRestrictedDocumentType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NotRestrictedDocumentType }{@code >}
     */
    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", name = "PassportLossCertificate")
    public JAXBElement<NotRestrictedDocumentType> createPassportLossCertificate(NotRestrictedDocumentType value) {
        return new JAXBElement<NotRestrictedDocumentType>(_PassportLossCertificate_QNAME, NotRestrictedDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotRestrictedDocumentType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NotRestrictedDocumentType }{@code >}
     */
    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", name = "Form9Certificate")
    public JAXBElement<NotRestrictedDocumentType> createForm9Certificate(NotRestrictedDocumentType value) {
        return new JAXBElement<NotRestrictedDocumentType>(_Form9Certificate_QNAME, NotRestrictedDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotRestrictedDocumentType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NotRestrictedDocumentType }{@code >}
     */
    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", name = "TemporaryIdentityCardRF")
    public JAXBElement<NotRestrictedDocumentType> createTemporaryIdentityCardRF(NotRestrictedDocumentType value) {
        return new JAXBElement<NotRestrictedDocumentType>(_TemporaryIdentityCardRF_QNAME, NotRestrictedDocumentType.class, null, value);
    }

}
