//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.02.22 at 11:45:16 AM YEKT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn://x-artefacts-rosreestr-ru/commons/complex-types/entity-spatial/5.0.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package converter.kpt.kpt;
