//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.02.22 at 11:45:16 AM YEKT 
//


package converter.kpt.kpt;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Основной документ, удостоверяющий личность
 * 
 * <p>Java class for PrimaryIdentityDocumentType complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PrimaryIdentityDocumentType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;group ref="{urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1}PrimaryIdentityDocument-ModelGroup"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrimaryIdentityDocumentType", namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", propOrder = {
    "passportRF",
    "foreignPassport",
    "residencePermitRF"
})
public class PrimaryIdentityDocumentType {

    @XmlElement(name = "PassportRF")
    protected PassportRFType passportRF;
    @XmlElement(name = "ForeignPassport")
    protected NotRestrictedDocumentType foreignPassport;
    @XmlElement(name = "ResidencePermitRF")
    protected InternationalPassportRFType residencePermitRF;

    /**
     * Gets the value of the passportRF property.
     * 
     * @return
     *     possible object is
     *     {@link PassportRFType }
     *     
     */
    public PassportRFType getPassportRF() {
        return passportRF;
    }

    /**
     * Sets the value of the passportRF property.
     * 
     * @param value
     *     allowed object is
     *     {@link PassportRFType }
     *     
     */
    public void setPassportRF(PassportRFType value) {
        this.passportRF = value;
    }

    /**
     * Gets the value of the foreignPassport property.
     * 
     * @return
     *     possible object is
     *     {@link NotRestrictedDocumentType }
     *     
     */
    public NotRestrictedDocumentType getForeignPassport() {
        return foreignPassport;
    }

    /**
     * Sets the value of the foreignPassport property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotRestrictedDocumentType }
     *     
     */
    public void setForeignPassport(NotRestrictedDocumentType value) {
        this.foreignPassport = value;
    }

    /**
     * Gets the value of the residencePermitRF property.
     * 
     * @return
     *     possible object is
     *     {@link InternationalPassportRFType }
     *     
     */
    public InternationalPassportRFType getResidencePermitRF() {
        return residencePermitRF;
    }

    /**
     * Sets the value of the residencePermitRF property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternationalPassportRFType }
     *     
     */
    public void setResidencePermitRF(InternationalPassportRFType value) {
        this.residencePermitRF = value;
    }

}
