//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.02.22 at 11:45:16 AM YEKT 
//


package converter.kpt.kpt;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;
import java.math.BigInteger;


/**
 * Площадь с округлением до 1 кв. м и погрешность определения площади
 * 
 * <p>Java class for tAreaOut complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tAreaOut"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Area" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/2.0.1}nn20"/&gt;
 *         &lt;element name="Unit" type="{urn://x-artefacts-rosreestr-ru/commons/directories/unit/1.0.1}dUnit"/&gt;
 *         &lt;element name="Inaccuracy" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/1.0}d20_2" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tAreaOut", namespace = "urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1", propOrder = {
    "area",
    "unit",
    "inaccuracy"
})
public class TAreaOut {

    @XmlElement(name = "Area", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger area;
    @XmlElement(name = "Unit", required = true)
    protected String unit;
    @XmlElement(name = "Inaccuracy")
    protected BigDecimal inaccuracy;

    /**
     * Gets the value of the area property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getArea() {
        return area;
    }

    /**
     * Sets the value of the area property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setArea(BigInteger value) {
        this.area = value;
    }

    /**
     * Gets the value of the unit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnit() {
        return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnit(String value) {
        this.unit = value;
    }

    /**
     * Gets the value of the inaccuracy property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInaccuracy() {
        return inaccuracy;
    }

    /**
     * Sets the value of the inaccuracy property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInaccuracy(BigDecimal value) {
        this.inaccuracy = value;
    }

}
