//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.02.22 at 11:45:16 AM YEKT 
//


package converter.kpt.kpt;

import javax.xml.bind.annotation.*;


/**
 * Часть границы (от точки до точки) и отметка о наличии земельного спора
 * 
 * <p>Java class for tBorderAgreement complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tBorderAgreement"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn://x-artefacts-rosreestr-ru/commons/complex-types/entity-spatial/5.0.1}tBorder"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Edge" type="{urn://x-artefacts-rosreestr-ru/commons/complex-types/entity-spatial/5.0.1}tLength"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="LandDispute" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/2.0.1}s150" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tBorderAgreement", propOrder = {
    "edge"
})
public class TBorderAgreement
    extends TBorder
{

    @XmlElement(name = "Edge", required = true)
    protected TLength edge;
    @XmlAttribute(name = "LandDispute")
    protected String landDispute;

    /**
     * Gets the value of the edge property.
     * 
     * @return
     *     possible object is
     *     {@link TLength }
     *     
     */
    public TLength getEdge() {
        return edge;
    }

    /**
     * Sets the value of the edge property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLength }
     *     
     */
    public void setEdge(TLength value) {
        this.edge = value;
    }

    /**
     * Gets the value of the landDispute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLandDispute() {
        return landDispute;
    }

    /**
     * Sets the value of the landDispute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLandDispute(String value) {
        this.landDispute = value;
    }

}
