//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.02.22 at 11:45:16 AM YEKT 
//


package converter.kpt.kpt;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * Обозначение части границы (от точки до точки)
 * 
 * <p>Java class for tBorder complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tBorder"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="Spatial" use="required" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/2.0.1}p22Min1" /&gt;
 *       &lt;attribute name="Point1" use="required" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/2.0.1}p22Min1" /&gt;
 *       &lt;attribute name="Point2" use="required" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/2.0.1}p22Min1" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tBorder")
@XmlSeeAlso({
    TBorderAgreement.class,
        converter.kpt.kpt.TBordersInp.Border.class,
        converter.kpt.kpt.TEntitySpatialBordersZUOut.Borders.Border.class,
    TBorderLand.class
})
public class TBorder {

    @XmlAttribute(name = "Spatial", required = true)
    protected BigInteger spatial;
    @XmlAttribute(name = "Point1", required = true)
    protected BigInteger point1;
    @XmlAttribute(name = "Point2", required = true)
    protected BigInteger point2;

    /**
     * Gets the value of the spatial property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSpatial() {
        return spatial;
    }

    /**
     * Sets the value of the spatial property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSpatial(BigInteger value) {
        this.spatial = value;
    }

    /**
     * Gets the value of the point1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPoint1() {
        return point1;
    }

    /**
     * Sets the value of the point1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPoint1(BigInteger value) {
        this.point1 = value;
    }

    /**
     * Gets the value of the point2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPoint2() {
        return point2;
    }

    /**
     * Sets the value of the point2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPoint2(BigInteger value) {
        this.point2 = value;
    }

}
