//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.02.22 at 11:45:16 AM YEKT 
//


package converter.kpt.kpt;

import com.uriit.kptConverter.CRSEnum;
import com.uriit.kptConverter.info.CadastralBlockInfo;
import com.uriit.kptConverter.utils.Dictonary;
import com.uriit.kptConverter.utils.FSHelper;
import com.uriit.kptConverter.utils.Utils;
import converter.kpt.exceptions.CustomException;
import mil.nga.sf.geojson.*;
import mil.nga.sf.util.SFException;

import javax.xml.bind.annotation.*;
import java.io.File;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;


/**
 * Кадастровый квартал
 * 
 * <p>Java class for tCadastralBlock complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tCadastralBlock"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Area" type="{urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1}tAreaCadastralBlock"/&gt;
 *         &lt;element name="Parcels" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Parcel" type="{urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1}tParcel" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ObjectsRealty" type="{urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1}tObjectsRealty" minOccurs="0"/&gt;
 *         &lt;element name="OMSPoints" type="{urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1}tOMSPoints" minOccurs="0"/&gt;
 *         &lt;element name="SpatialData" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="EntitySpatial" type="{urn://x-artefacts-rosreestr-ru/commons/complex-types/entity-spatial/5.0.1}tEntitySpatialLandOut"/&gt;
 *                   &lt;element name="Documents" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Document" type="{urn://x-artefacts-rosreestr-ru/commons/complex-types/document-output/4.0.1}tDocumentWithoutAppliedFile" maxOccurs="unbounded"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Bounds" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Bound" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Description" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/1.0}s1000"/&gt;
 *                             &lt;element name="AccountNumber" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/1.0}s255"/&gt;
 *                             &lt;element name="Boundaries" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="Boundary" maxOccurs="unbounded"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name="EntitySpatial" type="{urn://x-artefacts-rosreestr-ru/commons/complex-types/entity-spatial/5.0.1}tEntitySpatialLandOut"/&gt;
 *                                               &lt;/sequence&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="Documents" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="Document" type="{urn://x-artefacts-rosreestr-ru/commons/complex-types/document-output/4.0.1}tDocumentWithoutAppliedFile" maxOccurs="unbounded"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;choice&gt;
 *                               &lt;element name="SubjectsBoundary"&gt;
 *                                 &lt;complexType&gt;
 *                                   &lt;complexContent&gt;
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                       &lt;sequence&gt;
 *                                         &lt;element name="NameNeighbours" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/1.0}s255" maxOccurs="2" minOccurs="2"/&gt;
 *                                       &lt;/sequence&gt;
 *                                     &lt;/restriction&gt;
 *                                   &lt;/complexContent&gt;
 *                                 &lt;/complexType&gt;
 *                               &lt;/element&gt;
 *                               &lt;element name="MunicipalBoundary" type="{urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1}tName"/&gt;
 *                               &lt;element name="InhabitedLocalityBoundary" type="{urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1}tName"/&gt;
 *                             &lt;/choice&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Zones" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Zone" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Description" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/1.0}s1000"/&gt;
 *                             &lt;element name="AccountNumber" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/1.0}s255"/&gt;
 *                             &lt;element name="EntitySpatial" type="{urn://x-artefacts-rosreestr-ru/commons/complex-types/entity-spatial/5.0.1}tEntitySpatialLandOut"/&gt;
 *                             &lt;element name="Documents" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="Document" type="{urn://x-artefacts-rosreestr-ru/commons/complex-types/document-output/4.0.1}tDocumentWithoutAppliedFile" maxOccurs="unbounded"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;choice&gt;
 *                               &lt;element name="TerritorialZone" type="{urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1}tTerritorialZone"/&gt;
 *                               &lt;element name="SpecialZone" type="{urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1}tSpecialZones"/&gt;
 *                             &lt;/choice&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CoordSystems" type="{urn://x-artefacts-rosreestr-ru/commons/complex-types/entity-spatial/5.0.1}tCoordSystems" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="CadastralNumber" use="required" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/1.0}s40" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tCadastralBlock", namespace = "urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1", propOrder = {
    "area",
    "parcels",
    "objectsRealty",
    "omsPoints",
    "spatialData",
    "bounds",
    "zones",
    "coordSystems"
})
public class TCadastralBlock {

    @XmlElement(name = "Area", required = true)
    protected TAreaCadastralBlock area;
    @XmlElement(name = "Parcels")
    protected TCadastralBlock.Parcels parcels;
    @XmlElement(name = "ObjectsRealty")
    protected TObjectsRealty objectsRealty;
    @XmlElement(name = "OMSPoints")
    protected TOMSPoints omsPoints;
    @XmlElement(name = "SpatialData")
    protected TCadastralBlock.SpatialData spatialData;
    @XmlElement(name = "Bounds")
    protected TCadastralBlock.Bounds bounds;
    @XmlElement(name = "Zones")
    protected TCadastralBlock.Zones zones;
    @XmlElement(name = "CoordSystems")
    protected TCoordSystems coordSystems;
    @XmlAttribute(name = "CadastralNumber", required = true)
    protected String cadastralNumber;

    /**
     * Gets the value of the area property.
     *
     * @return
     *     possible object is
     *     {@link TAreaCadastralBlock }
     *
     */
    public TAreaCadastralBlock getArea() {
        return area;
    }

    /**
     * Sets the value of the area property.
     *
     * @param value
     *     allowed object is
     *     {@link TAreaCadastralBlock }
     *
     */
    public void setArea(TAreaCadastralBlock value) {
        this.area = value;
    }

    /**
     * Gets the value of the parcels property.
     *
     * @return
     *     possible object is
     *     {@link TCadastralBlock.Parcels }
     *
     */
    public TCadastralBlock.Parcels getParcels() {
        return parcels;
    }

    /**
     * Sets the value of the parcels property.
     *
     * @param value
     *     allowed object is
     *     {@link TCadastralBlock.Parcels }
     *
     */
    public void setParcels(TCadastralBlock.Parcels value) {
        this.parcels = value;
    }

    /**
     * Gets the value of the objectsRealty property.
     *
     * @return
     *     possible object is
     *     {@link TObjectsRealty }
     *
     */
    public TObjectsRealty getObjectsRealty() {
        return objectsRealty;
    }

    /**
     * Sets the value of the objectsRealty property.
     *
     * @param value
     *     allowed object is
     *     {@link TObjectsRealty }
     *
     */
    public void setObjectsRealty(TObjectsRealty value) {
        this.objectsRealty = value;
    }

    /**
     * Gets the value of the omsPoints property.
     *
     * @return
     *     possible object is
     *     {@link TOMSPoints }
     *
     */
    public TOMSPoints getOMSPoints() {
        return omsPoints;
    }

    /**
     * Sets the value of the omsPoints property.
     *
     * @param value
     *     allowed object is
     *     {@link TOMSPoints }
     *
     */
    public void setOMSPoints(TOMSPoints value) {
        this.omsPoints = value;
    }

    /**
     * Gets the value of the spatialData property.
     *
     * @return
     *     possible object is
     *     {@link TCadastralBlock.SpatialData }
     *
     */
    public TCadastralBlock.SpatialData getSpatialData() {
        return spatialData;
    }

    /**
     * Sets the value of the spatialData property.
     *
     * @param value
     *     allowed object is
     *     {@link TCadastralBlock.SpatialData }
     *
     */
    public void setSpatialData(TCadastralBlock.SpatialData value) {
        this.spatialData = value;
    }

    /**
     * Gets the value of the bounds property.
     *
     * @return
     *     possible object is
     *     {@link TCadastralBlock.Bounds }
     *
     */
    public TCadastralBlock.Bounds getBounds() {
        return bounds;
    }

    /**
     * Sets the value of the bounds property.
     *
     * @param value
     *     allowed object is
     *     {@link TCadastralBlock.Bounds }
     *
     */
    public void setBounds(TCadastralBlock.Bounds value) {
        this.bounds = value;
    }

    /**
     * Gets the value of the zones property.
     *
     * @return
     *     possible object is
     *     {@link TCadastralBlock.Zones }
     *
     */
    public TCadastralBlock.Zones getZones() {
        return zones;
    }

    /**
     * Sets the value of the zones property.
     *
     * @param value
     *     allowed object is
     *     {@link TCadastralBlock.Zones }
     *
     */
    public void setZones(TCadastralBlock.Zones value) {
        this.zones = value;
    }

    /**
     * Gets the value of the coordSystems property.
     *
     * @return
     *     possible object is
     *     {@link TCoordSystems }
     *
     */
    public TCoordSystems getCoordSystems() {
        return coordSystems;
    }

    /**
     * Sets the value of the coordSystems property.
     *
     * @param value
     *     allowed object is
     *     {@link TCoordSystems }
     *
     */
    public void setCoordSystems(TCoordSystems value) {
        this.coordSystems = value;
    }

    /**
     * Gets the value of the cadastralNumber property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCadastralNumber() {
        return cadastralNumber;
    }

    /**
     * Sets the value of the cadastralNumber property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCadastralNumber(String value) {
        this.cadastralNumber = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected         content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Bound" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="Description" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/1.0}s1000"/&gt;
     *                   &lt;element name="AccountNumber" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/1.0}s255"/&gt;
     *                   &lt;element name="Boundaries" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="Boundary" maxOccurs="unbounded"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;sequence&gt;
     *                                       &lt;element name="EntitySpatial" type="{urn://x-artefacts-rosreestr-ru/commons/complex-types/entity-spatial/5.0.1}tEntitySpatialLandOut"/&gt;
     *                                     &lt;/sequence&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="Documents" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="Document" type="{urn://x-artefacts-rosreestr-ru/commons/complex-types/document-output/4.0.1}tDocumentWithoutAppliedFile" maxOccurs="unbounded"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;choice&gt;
     *                     &lt;element name="SubjectsBoundary"&gt;
     *                       &lt;complexType&gt;
     *                         &lt;complexContent&gt;
     *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                             &lt;sequence&gt;
     *                               &lt;element name="NameNeighbours" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/1.0}s255" maxOccurs="2" minOccurs="2"/&gt;
     *                             &lt;/sequence&gt;
     *                           &lt;/restriction&gt;
     *                         &lt;/complexContent&gt;
     *                       &lt;/complexType&gt;
     *                     &lt;/element&gt;
     *                     &lt;element name="MunicipalBoundary" type="{urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1}tName"/&gt;
     *                     &lt;element name="InhabitedLocalityBoundary" type="{urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1}tName"/&gt;
     *                   &lt;/choice&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bound"
    })
    public static class Bounds {

        @XmlElement(name = "Bound", namespace = "urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1", required = true)
        protected List<Bound> bound;

        /**
         * Gets the value of the bound property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the bound property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBound().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TCadastralBlock.Bounds.Bound }
         *
         *
         */
        public List<Bound> getBound() {
            if (bound == null) {
                bound = new ArrayList<Bound>();
            }
            return this.bound;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected         content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="Description" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/1.0}s1000"/&gt;
         *         &lt;element name="AccountNumber" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/1.0}s255"/&gt;
         *         &lt;element name="Boundaries" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="Boundary" maxOccurs="unbounded"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;sequence&gt;
         *                             &lt;element name="EntitySpatial" type="{urn://x-artefacts-rosreestr-ru/commons/complex-types/entity-spatial/5.0.1}tEntitySpatialLandOut"/&gt;
         *                           &lt;/sequence&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="Documents" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="Document" type="{urn://x-artefacts-rosreestr-ru/commons/complex-types/document-output/4.0.1}tDocumentWithoutAppliedFile" maxOccurs="unbounded"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;choice&gt;
         *           &lt;element name="SubjectsBoundary"&gt;
         *             &lt;complexType&gt;
         *               &lt;complexContent&gt;
         *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                   &lt;sequence&gt;
         *                     &lt;element name="NameNeighbours" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/1.0}s255" maxOccurs="2" minOccurs="2"/&gt;
         *                   &lt;/sequence&gt;
         *                 &lt;/restriction&gt;
         *               &lt;/complexContent&gt;
         *             &lt;/complexType&gt;
         *           &lt;/element&gt;
         *           &lt;element name="MunicipalBoundary" type="{urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1}tName"/&gt;
         *           &lt;element name="InhabitedLocalityBoundary" type="{urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1}tName"/&gt;
         *         &lt;/choice&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "description",
            "accountNumber",
            "boundaries",
            "documents",
            "subjectsBoundary",
            "municipalBoundary",
            "inhabitedLocalityBoundary"
        })
        public static class Bound {

            @XmlElement(name = "Description", namespace = "urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1", required = true)
            protected String description;
            @XmlElement(name = "AccountNumber", namespace = "urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1", required = true)
            protected String accountNumber;
            @XmlElement(name = "Boundaries", namespace = "urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")
            protected TCadastralBlock.Bounds.Bound.Boundaries boundaries;
            @XmlElement(name = "Documents", namespace = "urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")
            protected TCadastralBlock.Bounds.Bound.Documents documents;
            @XmlElement(name = "SubjectsBoundary", namespace = "urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")
            protected TCadastralBlock.Bounds.Bound.SubjectsBoundary subjectsBoundary;
            @XmlElement(name = "MunicipalBoundary", namespace = "urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")
            protected TName municipalBoundary;
            @XmlElement(name = "InhabitedLocalityBoundary", namespace = "urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")
            protected TName inhabitedLocalityBoundary;

            /**
             * Gets the value of the description property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the accountNumber property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getAccountNumber() {
                return accountNumber;
            }

            /**
             * Sets the value of the accountNumber property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setAccountNumber(String value) {
                this.accountNumber = value;
            }

            /**
             * Gets the value of the boundaries property.
             *
             * @return
             *     possible object is
             *     {@link TCadastralBlock.Bounds.Bound.Boundaries }
             *
             */
            public TCadastralBlock.Bounds.Bound.Boundaries getBoundaries() {
                return boundaries;
            }

            /**
             * Sets the value of the boundaries property.
             *
             * @param value
             *     allowed object is
             *     {@link TCadastralBlock.Bounds.Bound.Boundaries }
             *
             */
            public void setBoundaries(TCadastralBlock.Bounds.Bound.Boundaries value) {
                this.boundaries = value;
            }

            /**
             * Gets the value of the documents property.
             *
             * @return
             *     possible object is
             *     {@link TCadastralBlock.Bounds.Bound.Documents }
             *
             */
            public TCadastralBlock.Bounds.Bound.Documents getDocuments() {
                return documents;
            }

            /**
             * Sets the value of the documents property.
             *
             * @param value
             *     allowed object is
             *     {@link TCadastralBlock.Bounds.Bound.Documents }
             *
             */
            public void setDocuments(TCadastralBlock.Bounds.Bound.Documents value) {
                this.documents = value;
            }

            /**
             * Gets the value of the subjectsBoundary property.
             *
             * @return
             *     possible object is
             *     {@link TCadastralBlock.Bounds.Bound.SubjectsBoundary }
             *
             */
            public TCadastralBlock.Bounds.Bound.SubjectsBoundary getSubjectsBoundary() {
                return subjectsBoundary;
            }

            /**
             * Sets the value of the subjectsBoundary property.
             *
             * @param value
             *     allowed object is
             *     {@link TCadastralBlock.Bounds.Bound.SubjectsBoundary }
             *
             */
            public void setSubjectsBoundary(TCadastralBlock.Bounds.Bound.SubjectsBoundary value) {
                this.subjectsBoundary = value;
            }

            /**
             * Gets the value of the municipalBoundary property.
             *
             * @return
             *     possible object is
             *     {@link TName }
             *
             */
            public TName getMunicipalBoundary() {
                return municipalBoundary;
            }

            /**
             * Sets the value of the municipalBoundary property.
             *
             * @param value
             *     allowed object is
             *     {@link TName }
             *
             */
            public void setMunicipalBoundary(TName value) {
                this.municipalBoundary = value;
            }

            /**
             * Gets the value of the inhabitedLocalityBoundary property.
             *
             * @return
             *     possible object is
             *     {@link TName }
             *
             */
            public TName getInhabitedLocalityBoundary() {
                return inhabitedLocalityBoundary;
            }

            /**
             * Sets the value of the inhabitedLocalityBoundary property.
             *
             * @param value
             *     allowed object is
             *     {@link TName }
             *
             */
            public void setInhabitedLocalityBoundary(TName value) {
                this.inhabitedLocalityBoundary = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected         content contained within this class.
             *
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="Boundary" maxOccurs="unbounded"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element name="EntitySpatial" type="{urn://x-artefacts-rosreestr-ru/commons/complex-types/entity-spatial/5.0.1}tEntitySpatialLandOut"/&gt;
             *                 &lt;/sequence&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "boundary"
            })
            public static class Boundaries {

                @XmlElement(name = "Boundary", namespace = "urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1", required = true)
                protected List<Boundary> boundary;

                /**
                 * Gets the value of the boundary property.
                 *
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the boundary property.
                 *
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getBoundary().add(newItem);
                 * </pre>
                 *
                 *
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link TCadastralBlock.Bounds.Bound.Boundaries.Boundary }
                 *
                 *
                 */
                public List<Boundary> getBoundary() {
                    if (boundary == null) {
                        boundary = new ArrayList<Boundary>();
                    }
                    return this.boundary;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 *
                 * <p>The following schema fragment specifies the expected         content contained within this class.
                 *
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element name="EntitySpatial" type="{urn://x-artefacts-rosreestr-ru/commons/complex-types/entity-spatial/5.0.1}tEntitySpatialLandOut"/&gt;
                 *       &lt;/sequence&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 *
                 *
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "entitySpatial"
                })
                public static class Boundary {

                    @XmlElement(name = "EntitySpatial", namespace = "urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1", required = true)
                    protected TEntitySpatialLandOut entitySpatial;

                    /**
                     * Gets the value of the entitySpatial property.
                     *
                     * @return
                     *     possible object is
                     *     {@link TEntitySpatialLandOut }
                     *
                     */
                    public TEntitySpatialLandOut getEntitySpatial() {
                        return entitySpatial;
                    }

                    /**
                     * Sets the value of the entitySpatial property.
                     *
                     * @param value
                     *     allowed object is
                     *     {@link TEntitySpatialLandOut }
                     *
                     */
                    public void setEntitySpatial(TEntitySpatialLandOut value) {
                        this.entitySpatial = value;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected         content contained within this class.
             *
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="Document" type="{urn://x-artefacts-rosreestr-ru/commons/complex-types/document-output/4.0.1}tDocumentWithoutAppliedFile" maxOccurs="unbounded"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "document"
            })
            public static class Documents {

                @XmlElement(name = "Document", namespace = "urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1", required = true)
                protected List<TDocumentWithoutAppliedFile> document;

                /**
                 * Gets the value of the document property.
                 *
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the document property.
                 *
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getDocument().add(newItem);
                 * </pre>
                 *
                 *
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link TDocumentWithoutAppliedFile }
                 *
                 *
                 */
                public List<TDocumentWithoutAppliedFile> getDocument() {
                    if (document == null) {
                        document = new ArrayList<TDocumentWithoutAppliedFile>();
                    }
                    return this.document;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected         content contained within this class.
             *
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="NameNeighbours" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/1.0}s255" maxOccurs="2" minOccurs="2"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "nameNeighbours"
            })
            public static class SubjectsBoundary {

                @XmlElement(name = "NameNeighbours", namespace = "urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1", required = true)
                protected List<String> nameNeighbours;

                /**
                 * Gets the value of the nameNeighbours property.
                 *
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the nameNeighbours property.
                 *
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getNameNeighbours().add(newItem);
                 * </pre>
                 *
                 *
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 *
                 *
                 */
                public List<String> getNameNeighbours() {
                    if (nameNeighbours == null) {
                        nameNeighbours = new ArrayList<String>();
                    }
                    return this.nameNeighbours;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected         content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Parcel" type="{urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1}tParcel" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "parcel"
    })
    public static class Parcels {

        @XmlElement(name = "Parcel", namespace = "urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1", required = true)
        protected List<TParcel> parcel;

        /**
         * Gets the value of the parcel property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the parcel property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParcel().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TParcel }
         *
         *
         */
        public List<TParcel> getParcel() {
            if (parcel == null) {
                parcel = new ArrayList<TParcel>();
            }
            return this.parcel;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected         content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="EntitySpatial" type="{urn://x-artefacts-rosreestr-ru/commons/complex-types/entity-spatial/5.0.1}tEntitySpatialLandOut"/&gt;
     *         &lt;element name="Documents" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="Document" type="{urn://x-artefacts-rosreestr-ru/commons/complex-types/document-output/4.0.1}tDocumentWithoutAppliedFile" maxOccurs="unbounded"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "entitySpatial",
        "documents"
    })
    public static class SpatialData {

        @XmlElement(name = "EntitySpatial", namespace = "urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1", required = true)
        protected TEntitySpatialLandOut entitySpatial;
        @XmlElement(name = "Documents", namespace = "urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")
        protected TCadastralBlock.SpatialData.Documents documents;

        /**
         * Gets the value of the entitySpatial property.
         *
         * @return
         *     possible object is
         *     {@link TEntitySpatialLandOut }
         *
         */
        public TEntitySpatialLandOut getEntitySpatial() {
            return entitySpatial;
        }

        /**
         * Sets the value of the entitySpatial property.
         *
         * @param value
         *     allowed object is
         *     {@link TEntitySpatialLandOut }
         *
         */
        public void setEntitySpatial(TEntitySpatialLandOut value) {
            this.entitySpatial = value;
        }

        /**
         * Gets the value of the documents property.
         *
         * @return
         *     possible object is
         *     {@link TCadastralBlock.SpatialData.Documents }
         *
         */
        public TCadastralBlock.SpatialData.Documents getDocuments() {
            return documents;
        }

        /**
         * Sets the value of the documents property.
         *
         * @param value
         *     allowed object is
         *     {@link TCadastralBlock.SpatialData.Documents }
         *
         */
        public void setDocuments(TCadastralBlock.SpatialData.Documents value) {
            this.documents = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected         content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="Document" type="{urn://x-artefacts-rosreestr-ru/commons/complex-types/document-output/4.0.1}tDocumentWithoutAppliedFile" maxOccurs="unbounded"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "document"
        })
        public static class Documents {

            @XmlElement(name = "Document", namespace = "urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1", required = true)
            protected List<TDocumentWithoutAppliedFile> document;

            /**
             * Gets the value of the document property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the document property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDocument().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link TDocumentWithoutAppliedFile }
             *
             *
             */
            public List<TDocumentWithoutAppliedFile> getDocument() {
                if (document == null) {
                    document = new ArrayList<TDocumentWithoutAppliedFile>();
                }
                return this.document;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected         content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Zone" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="Description" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/1.0}s1000"/&gt;
     *                   &lt;element name="AccountNumber" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/1.0}s255"/&gt;
     *                   &lt;element name="EntitySpatial" type="{urn://x-artefacts-rosreestr-ru/commons/complex-types/entity-spatial/5.0.1}tEntitySpatialLandOut"/&gt;
     *                   &lt;element name="Documents" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="Document" type="{urn://x-artefacts-rosreestr-ru/commons/complex-types/document-output/4.0.1}tDocumentWithoutAppliedFile" maxOccurs="unbounded"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;choice&gt;
     *                     &lt;element name="TerritorialZone" type="{urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1}tTerritorialZone"/&gt;
     *                     &lt;element name="SpecialZone" type="{urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1}tSpecialZones"/&gt;
     *                   &lt;/choice&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "zone"
    })
    public static class Zones {

        @XmlElement(name = "Zone", namespace = "urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1", required = true)
        protected List<Zone> zone;

        /**
         * Gets the value of the zone property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the zone property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getZone().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TCadastralBlock.Zones.Zone }
         *
         *
         */
        public List<Zone> getZone() {
            if (zone == null) {
                zone = new ArrayList<Zone>();
            }
            return this.zone;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected         content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="Description" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/1.0}s1000"/&gt;
         *         &lt;element name="AccountNumber" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/1.0}s255"/&gt;
         *         &lt;element name="EntitySpatial" type="{urn://x-artefacts-rosreestr-ru/commons/complex-types/entity-spatial/5.0.1}tEntitySpatialLandOut"/&gt;
         *         &lt;element name="Documents" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="Document" type="{urn://x-artefacts-rosreestr-ru/commons/complex-types/document-output/4.0.1}tDocumentWithoutAppliedFile" maxOccurs="unbounded"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;choice&gt;
         *           &lt;element name="TerritorialZone" type="{urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1}tTerritorialZone"/&gt;
         *           &lt;element name="SpecialZone" type="{urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1}tSpecialZones"/&gt;
         *         &lt;/choice&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "description",
            "accountNumber",
            "entitySpatial",
            "documents",
            "territorialZone",
            "specialZone"
        })
        public static class Zone {

            @XmlElement(name = "Description", namespace = "urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1", required = true)
            protected String description;
            @XmlElement(name = "AccountNumber", namespace = "urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1", required = true)
            protected String accountNumber;
            @XmlElement(name = "EntitySpatial", namespace = "urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1", required = true)
            protected TEntitySpatialLandOut entitySpatial;
            @XmlElement(name = "Documents", namespace = "urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")
            protected TCadastralBlock.Zones.Zone.Documents documents;
            @XmlElement(name = "TerritorialZone", namespace = "urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")
            protected TTerritorialZone territorialZone;
            @XmlElement(name = "SpecialZone", namespace = "urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")
            protected TSpecialZones specialZone;

            /**
             * Gets the value of the description property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the accountNumber property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getAccountNumber() {
                return accountNumber;
            }

            /**
             * Sets the value of the accountNumber property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setAccountNumber(String value) {
                this.accountNumber = value;
            }

            /**
             * Gets the value of the entitySpatial property.
             *
             * @return
             *     possible object is
             *     {@link TEntitySpatialLandOut }
             *
             */
            public TEntitySpatialLandOut getEntitySpatial() {
                return entitySpatial;
            }

            /**
             * Sets the value of the entitySpatial property.
             *
             * @param value
             *     allowed object is
             *     {@link TEntitySpatialLandOut }
             *
             */
            public void setEntitySpatial(TEntitySpatialLandOut value) {
                this.entitySpatial = value;
            }

            /**
             * Gets the value of the documents property.
             *
             * @return
             *     possible object is
             *     {@link TCadastralBlock.Zones.Zone.Documents }
             *
             */
            public TCadastralBlock.Zones.Zone.Documents getDocuments() {
                return documents;
            }

            /**
             * Sets the value of the documents property.
             *
             * @param value
             *     allowed object is
             *     {@link TCadastralBlock.Zones.Zone.Documents }
             *
             */
            public void setDocuments(TCadastralBlock.Zones.Zone.Documents value) {
                this.documents = value;
            }

            /**
             * Gets the value of the territorialZone property.
             * 
             * @return
             *     possible object is
             *     {@link TTerritorialZone }
             *     
             */
            public TTerritorialZone getTerritorialZone() {
                return territorialZone;
            }

            /**
             * Sets the value of the territorialZone property.
             * 
             * @param value
             *     allowed object is
             *     {@link TTerritorialZone }
             *     
             */
            public void setTerritorialZone(TTerritorialZone value) {
                this.territorialZone = value;
            }

            /**
             * Gets the value of the specialZone property.
             * 
             * @return
             *     possible object is
             *     {@link TSpecialZones }
             *     
             */
            public TSpecialZones getSpecialZone() {
                return specialZone;
            }

            /**
             * Sets the value of the specialZone property.
             * 
             * @param value
             *     allowed object is
             *     {@link TSpecialZones }
             *     
             */
            public void setSpecialZone(TSpecialZones value) {
                this.specialZone = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected         content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="Document" type="{urn://x-artefacts-rosreestr-ru/commons/complex-types/document-output/4.0.1}tDocumentWithoutAppliedFile" maxOccurs="unbounded"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "document"
            })
            public static class Documents {

                @XmlElement(name = "Document", namespace = "urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1", required = true)
                protected List<TDocumentWithoutAppliedFile> document;

                /**
                 * Gets the value of the document property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the document property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getDocument().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link TDocumentWithoutAppliedFile }
                 * 
                 * 
                 */
                public List<TDocumentWithoutAppliedFile> getDocument() {
                    if (document == null) {
                        document = new ArrayList<TDocumentWithoutAppliedFile>();
                    }
                    return this.document;
                }

            }

        }

    }

    /*
    @XmlTransient
    private Map<String, CRSEnum> crsMap = null;

    @XmlTransient
    public Map<String, CRSEnum> getCRS() {
        if (crsMap == null) {
            crsMap = new HashMap<String, CRSEnum>();

            for (TCoordSystem cs: getCoordSystems().getCoordSystem()) {
                crsMap.put(cs.getCsId(), CRSEnum.get(cs.getName()));
            }
        }

        return crsMap;
    }*/

    @XmlTransient
    private CRSEnum crsEnum = null;

    @XmlTransient
    public CRSEnum getCRSEnum() {
        if (crsEnum == null) {
            if (coordSystems.getCoordSystem().size() == 1)
                crsEnum = CRSEnum.get(coordSystems.getCoordSystem().get(0).getName());
        }

        return crsEnum;
    }

    @XmlTransient
    private Path desstination;
    @XmlTransient
    private CadastralBlockInfo cbInfo;

    public void saveGeoJSON(Path desstination, CadastralBlockInfo cbInfo) throws CustomException {
        this.desstination = desstination;
        this.cbInfo = cbInfo;
        cbInfo.setCadastralNumber(getCadastralNumber());
        cbInfo.setExportFolder(desstination.toString());

        FeatureCollection fc = new FeatureCollection();
        fc.setCrs(getCRSEnum().getCRS());
        Feature f = new Feature();

        List<List<Position>> rings = new ArrayList<List<Position>>();
        List<Position> positions = new ArrayList<Position>();
        rings.add(positions);

        for (TSpatialElementLandOut e: this.getSpatialData().getEntitySpatial().getSpatialElement()) {
            for (TSpelementUnitLandOut u: e.getSpelementUnit()) {
                positions.add(new Position(u.getOrdinate().getY().doubleValue(), u.getOrdinate().getX().doubleValue()));
            }
        }

        Polygon p = new Polygon(rings);

        Map<String, Object> prop = new LinkedHashMap<String, Object>();
        prop.put("Кадастровый номер", getCadastralNumber());
        prop.put("Площадь", getArea().getTotal());
        prop.put("Площадь ед.изм.", Dictonary.getUnits(getArea().getUnit()));

        int parcelCnt = 0;
        if (getParcels() != null && getParcels().getParcel() != null)
            parcelCnt = getParcels().getParcel().size();
        prop.put("Участков", parcelCnt);

        int ORCnt = 0;
        if (getObjectsRealty() != null && getObjectsRealty().getObjectRealty() != null)
            ORCnt = getObjectsRealty().getObjectRealty().size();
        prop.put("ОКС", ORCnt);

        f.setGeometry(p);
        f.setProperties(prop);
        f.setId(getCadastralNumber());

        fc.addFeature(f);

        FSHelper.saveTextFile(new File(desstination.toString(), "CadastralBlock.geojson"), FeatureConverter.toStringValue(fc));

        saveParcelsGJ();
    }

    private void saveParcelsGJ() throws CustomException {
        FeatureCollection fc = new FeatureCollection();
        fc.setCrs(getCRSEnum().getCRS());

        for (TParcel parcel :getParcels().getParcel()) {
            cbInfo.getStatistics().incParcelsCnt(1);
            Feature feature = new Feature();
            feature.setId(parcel.getCadastralNumber());

            List<List<Position>> rings = new ArrayList<List<Position>>();

            if (parcel.getEntitySpatial() != null) {
                for (TSpatialElementZUOut se : parcel.getEntitySpatial().getSpatialElement()) {
                    List<Position> positions = new ArrayList<Position>();
                    for (TSpelementUnitZUOut u : se.getSpelementUnit()) {
                        positions.add(new Position(u.getOrdinate().getY().doubleValue(), u.getOrdinate().getX().doubleValue()));
                    }
                    rings.add(positions);
                }

                cbInfo.getStatistics().incParcelsWGeoCnt(1);
            }

            Polygon p = null;
            try {
                p = new Polygon(rings);
            } catch (SFException ex) {
                cbInfo.setErrorMsg(parcel.getCadastralNumber() + " ошибка создания полигона. " + ex.getMessage());
            }

            Map<String, Object> prop = new LinkedHashMap<String, Object>();
            prop.put("Кадастровый номер", parcel.getCadastralNumber());
            prop.put("Статус", Dictonary.getState(parcel.getState()));
            prop.put("Адрес", parcel.getLocation().getAddress().getNote());
            prop.put("Категория земель", Dictonary.getCategory(parcel.getCategory()));
            //prop.put("Форма собственности", ) //не нашел в доккументации
            if (parcel.getCadastralCost() != null) {
                prop.put("Кадастровая стоимость", parcel.getCadastralCost().getValue());
                prop.put("Кадастровая стоимость, ед.изм.", Dictonary.getUnits(parcel.getCadastralCost().getUnit()));
            }

            if (parcel.getArea() != null) {
                prop.put("Уточненная площадь", parcel.getArea().getArea());
                prop.put("Уточненная площадь, ед.изм.", Dictonary.getUnits(parcel.getArea().getUnit()));
            }

            if (parcel.getUtilization() != null) {
                prop.put("Разрешенное использование", Dictonary.getUtilization(parcel.getUtilization().utilization));
                prop.put("Разрешенное использование, по документу", parcel.getUtilization().byDoc);
            }

            prop.put("Дата постановки на учет", Utils.XmlGCToStr(parcel.getDateCreated()));

            feature.setGeometry(p);
            feature.setProperties(prop);

            fc.addFeature(feature);
        }

        FSHelper.saveTextFile(new File(desstination.toString(), "Parcels.geojson"), FeatureConverter.toStringValue(fc));
    }
}
