//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.02.22 at 11:45:16 AM YEKT 
//


package converter.kpt.kpt;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Реквизиты документа
 * 
 * <p>Java class for tDocumentWithoutAppliedFile complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tDocumentWithoutAppliedFile"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CodeDocument" type="{urn://x-artefacts-rosreestr-ru/commons/directories/all-documents-out/3.0.2}dAllDocuments"/&gt;
 *         &lt;element name="Name" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/1.0}s500" minOccurs="0"/&gt;
 *         &lt;element name="Series" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/1.0}s45" minOccurs="0"/&gt;
 *         &lt;element name="Number" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/1.0}s45" minOccurs="0"/&gt;
 *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="IssueOrgan" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/1.0}s500" minOccurs="0"/&gt;
 *         &lt;element name="Desc" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/1.0}s1000" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tDocumentWithoutAppliedFile", namespace = "urn://x-artefacts-rosreestr-ru/commons/complex-types/document-output/4.0.1", propOrder = {
    "codeDocument",
    "name",
    "series",
    "number",
    "date",
    "issueOrgan",
    "desc"
})
public class TDocumentWithoutAppliedFile {

    @XmlElement(name = "CodeDocument", required = true)
    protected String codeDocument;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Series")
    protected String series;
    @XmlElement(name = "Number")
    protected String number;
    @XmlElement(name = "Date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    @XmlElement(name = "IssueOrgan")
    protected String issueOrgan;
    @XmlElement(name = "Desc")
    protected String desc;

    /**
     * Gets the value of the codeDocument property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeDocument() {
        return codeDocument;
    }

    /**
     * Sets the value of the codeDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeDocument(String value) {
        this.codeDocument = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the series property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeries() {
        return series;
    }

    /**
     * Sets the value of the series property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeries(String value) {
        this.series = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the issueOrgan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssueOrgan() {
        return issueOrgan;
    }

    /**
     * Sets the value of the issueOrgan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssueOrgan(String value) {
        this.issueOrgan = value;
    }

    /**
     * Gets the value of the desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesc() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesc(String value) {
        this.desc = value;
    }

}
