//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.02.22 at 11:45:16 AM YEKT 
//


package converter.kpt.kpt;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Описание местоположения характерных точек границ и частей границ (от точки до точки) земельного участка
 * 
 * <p>Java class for tEntitySpatialBordersZUInp complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tEntitySpatialBordersZUInp"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn://x-artefacts-rosreestr-ru/commons/complex-types/entity-spatial/5.0.1}tEntitySpatialZUInp"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Borders" type="{urn://x-artefacts-rosreestr-ru/commons/complex-types/entity-spatial/5.0.1}tBordersInp" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tEntitySpatialBordersZUInp", propOrder = {
    "borders"
})
public class TEntitySpatialBordersZUInp
    extends TEntitySpatialZUInp
{

    @XmlElement(name = "Borders")
    protected TBordersInp borders;

    /**
     * Gets the value of the borders property.
     * 
     * @return
     *     possible object is
     *     {@link TBordersInp }
     *     
     */
    public TBordersInp getBorders() {
        return borders;
    }

    /**
     * Sets the value of the borders property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBordersInp }
     *     
     */
    public void setBorders(TBordersInp value) {
        this.borders = value;
    }

}
