//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.02.22 at 11:45:16 AM YEKT 
//


package converter.kpt.kpt;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * Описание местоположения характерных точек границ и частей границ (от точки до точки)
 * 
 * <p>Java class for tEntitySpatialBordersLand complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tEntitySpatialBordersLand"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn://x-artefacts-rosreestr-ru/commons/complex-types/entity-spatial/5.0.1}tEntitySpatialLandInp"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Borders" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Border" type="{urn://x-artefacts-rosreestr-ru/commons/complex-types/entity-spatial/5.0.1}tBorderLand" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tEntitySpatialBordersLand", propOrder = {
    "borders"
})
public class TEntitySpatialBordersLand
    extends TEntitySpatialLandInp
{

    @XmlElement(name = "Borders")
    protected TEntitySpatialBordersLand.Borders borders;

    /**
     * Gets the value of the borders property.
     *
     * @return
     *     possible object is
     *     {@link TEntitySpatialBordersLand.Borders }
     *
     */
    public TEntitySpatialBordersLand.Borders getBorders() {
        return borders;
    }

    /**
     * Sets the value of the borders property.
     *
     * @param value
     *     allowed object is
     *     {@link TEntitySpatialBordersLand.Borders }
     *
     */
    public void setBorders(TEntitySpatialBordersLand.Borders value) {
        this.borders = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Border" type="{urn://x-artefacts-rosreestr-ru/commons/complex-types/entity-spatial/5.0.1}tBorderLand" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "border"
    })
    public static class Borders {

        @XmlElement(name = "Border", required = true)
        protected List<TBorderLand> border;

        /**
         * Gets the value of the border property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the border property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBorder().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TBorderLand }
         * 
         * 
         */
        public List<TBorderLand> getBorder() {
            if (border == null) {
                border = new ArrayList<TBorderLand>();
            }
            return this.border;
        }

    }

}
