//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.02.22 at 11:45:16 AM YEKT 
//


package converter.kpt.kpt;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * Основные характеристики части
 * 
 * <p>Java class for tKeyParametersSubObject complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tKeyParametersSubObject"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="KeyParameterSubObject" type="{urn://x-artefacts-rosreestr-ru/commons/complex-types/parameters-oks/2.0.1}tKeyParameterSubObject" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tKeyParametersSubObject", namespace = "urn://x-artefacts-rosreestr-ru/commons/complex-types/parameters-oks/2.0.1", propOrder = {
    "keyParameterSubObject"
})
public class TKeyParametersSubObject {

    @XmlElement(name = "KeyParameterSubObject", required = true)
    protected List<TKeyParameterSubObject> keyParameterSubObject;

    /**
     * Gets the value of the keyParameterSubObject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the keyParameterSubObject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKeyParameterSubObject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TKeyParameterSubObject }
     * 
     * 
     */
    public List<TKeyParameterSubObject> getKeyParameterSubObject() {
        if (keyParameterSubObject == null) {
            keyParameterSubObject = new ArrayList<TKeyParameterSubObject>();
        }
        return this.keyParameterSubObject;
    }

}
