//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.02.22 at 11:45:16 AM YEKT 
//


package converter.kpt.kpt;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;


/**
 * Сведения о пунктах ОМС
 * 
 * <p>Java class for tOMSPoints complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tOMSPoints"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OMSPoint" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="PNmb" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/1.0}s4000"/&gt;
 *                   &lt;element name="PName" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/1.0}s4000"/&gt;
 *                   &lt;element name="PKlass" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/1.0}s4000"/&gt;
 *                   &lt;element name="OrdX" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/1.0}d38_2"/&gt;
 *                   &lt;element name="OrdY" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/1.0}d38_2"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tOMSPoints", namespace = "urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1", propOrder = {
    "omsPoint"
})
public class TOMSPoints {

    @XmlElement(name = "OMSPoint", required = true)
    protected List<OMSPoint> omsPoint;

    /**
     * Gets the value of the omsPoint property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the omsPoint property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOMSPoint().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TOMSPoints.OMSPoint }
     *
     *
     */
    public List<OMSPoint> getOMSPoint() {
        if (omsPoint == null) {
            omsPoint = new ArrayList<OMSPoint>();
        }
        return this.omsPoint;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="PNmb" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/1.0}s4000"/&gt;
     *         &lt;element name="PName" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/1.0}s4000"/&gt;
     *         &lt;element name="PKlass" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/1.0}s4000"/&gt;
     *         &lt;element name="OrdX" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/1.0}d38_2"/&gt;
     *         &lt;element name="OrdY" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/1.0}d38_2"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pNmb",
        "pName",
        "pKlass",
        "ordX",
        "ordY"
    })
    public static class OMSPoint {

        @XmlElement(name = "PNmb", namespace = "urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1", required = true)
        protected String pNmb;
        @XmlElement(name = "PName", namespace = "urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1", required = true)
        protected String pName;
        @XmlElement(name = "PKlass", namespace = "urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1", required = true)
        protected String pKlass;
        @XmlElement(name = "OrdX", namespace = "urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1", required = true)
        protected BigDecimal ordX;
        @XmlElement(name = "OrdY", namespace = "urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1", required = true)
        protected BigDecimal ordY;

        /**
         * Gets the value of the pNmb property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPNmb() {
            return pNmb;
        }

        /**
         * Sets the value of the pNmb property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPNmb(String value) {
            this.pNmb = value;
        }

        /**
         * Gets the value of the pName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPName() {
            return pName;
        }

        /**
         * Sets the value of the pName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPName(String value) {
            this.pName = value;
        }

        /**
         * Gets the value of the pKlass property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPKlass() {
            return pKlass;
        }

        /**
         * Sets the value of the pKlass property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPKlass(String value) {
            this.pKlass = value;
        }

        /**
         * Gets the value of the ordX property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getOrdX() {
            return ordX;
        }

        /**
         * Sets the value of the ordX property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setOrdX(BigDecimal value) {
            this.ordX = value;
        }

        /**
         * Gets the value of the ordY property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getOrdY() {
            return ordY;
        }

        /**
         * Sets the value of the ordY property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setOrdY(BigDecimal value) {
            this.ordY = value;
        }

    }

}
