//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.02.22 at 11:45:16 AM YEKT 
//


package converter.kpt.kpt;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Координата и метод определения точки
 * 
 * <p>Java class for tOrdinate complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tOrdinate"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn://x-artefacts-rosreestr-ru/commons/complex-types/entity-spatial/5.0.1}tOrdinateInp"&gt;
 *       &lt;attribute name="GeopointOpred" type="{urn://x-artefacts-rosreestr-ru/commons/directories/geopoint-opred/1.0.1}dGeopointOpred" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tOrdinate")
public class TOrdinate
    extends TOrdinateInp
{

    @XmlAttribute(name = "GeopointOpred")
    protected String geopointOpred;

    /**
     * Gets the value of the geopointOpred property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeopointOpred() {
        return geopointOpred;
    }

    /**
     * Sets the value of the geopointOpred property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeopointOpred(String value) {
        this.geopointOpred = value;
    }

}
