//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.02.22 at 11:45:16 AM YEKT 
//


package converter.kpt.kpt;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * Вид разрешенного использования
 * 
 * <p>Java class for tPermittedUseAll complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tPermittedUseAll"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1}tPermittedUse"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PermitedAncillary" type="{urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1}tPermittedUse" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tPermittedUseAll", namespace = "urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1", propOrder = {
    "permitedAncillary"
})
public class TPermittedUseAll
    extends TPermittedUse
{

    @XmlElement(name = "PermitedAncillary")
    protected List<TPermittedUse> permitedAncillary;

    /**
     * Gets the value of the permitedAncillary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the permitedAncillary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPermitedAncillary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TPermittedUse }
     * 
     * 
     */
    public List<TPermittedUse> getPermitedAncillary() {
        if (permitedAncillary == null) {
            permitedAncillary = new ArrayList<TPermittedUse>();
        }
        return this.permitedAncillary;
    }

}
