//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.02.22 at 11:45:16 AM YEKT 
//


package converter.kpt.kpt;

import javax.xml.bind.annotation.*;


/**
 * Часть элемента (точка)
 * 
 * <p>Java class for tSpelementUnit complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tSpelementUnit"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Ordinate" type="{urn://x-artefacts-rosreestr-ru/commons/complex-types/entity-spatial/5.0.1}tOrdinate"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="TypeUnit" use="required" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/1.0}sType_Unit" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tSpelementUnit", propOrder = {
    "ordinate"
})
public class TSpelementUnit {

    @XmlElement(name = "Ordinate", required = true)
    protected TOrdinate ordinate;
    @XmlAttribute(name = "TypeUnit", required = true)
    protected STypeUnit typeUnit;

    /**
     * Gets the value of the ordinate property.
     * 
     * @return
     *     possible object is
     *     {@link TOrdinate }
     *     
     */
    public TOrdinate getOrdinate() {
        return ordinate;
    }

    /**
     * Sets the value of the ordinate property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOrdinate }
     *     
     */
    public void setOrdinate(TOrdinate value) {
        this.ordinate = value;
    }

    /**
     * Gets the value of the typeUnit property.
     * 
     * @return
     *     possible object is
     *     {@link STypeUnit }
     *     
     */
    public STypeUnit getTypeUnit() {
        return typeUnit;
    }

    /**
     * Sets the value of the typeUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link STypeUnit }
     *     
     */
    public void setTypeUnit(STypeUnit value) {
        this.typeUnit = value;
    }

}
