//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.02.22 at 11:45:16 AM YEKT 
//


package converter.kpt.kpt;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Территориальная зона
 * 
 * <p>Java class for tTerritorialZone complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tTerritorialZone"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PermittedUses" type="{urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1}tPermittedUses"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tTerritorialZone", namespace = "urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1", propOrder = {
    "permittedUses"
})
public class TTerritorialZone {

    @XmlElement(name = "PermittedUses", required = true)
    protected TPermittedUses permittedUses;

    /**
     * Gets the value of the permittedUses property.
     * 
     * @return
     *     possible object is
     *     {@link TPermittedUses }
     *     
     */
    public TPermittedUses getPermittedUses() {
        return permittedUses;
    }

    /**
     * Sets the value of the permittedUses property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPermittedUses }
     *     
     */
    public void setPermittedUses(TPermittedUses value) {
        this.permittedUses = value;
    }

}
