//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.02.22 at 11:45:16 AM YEKT 
//


package converter.kpt.kpt;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Разрешенное использование
 * 
 * <p>Java class for tUtilization complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tUtilization"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="Utilization" type="{urn://x-artefacts-rosreestr-ru/commons/directories/utilizations/1.0.1}dUtilizations" /&gt;
 *       &lt;attribute name="ByDoc" type="{urn://x-artefacts-rosreestr-ru/commons/simple-types/1.0}s4000" /&gt;
 *       &lt;attribute name="LandUse" type="{urn://x-artefacts-rosreestr-ru/commons/directories/allowed-use/2.0.1}dAllowedUse" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tUtilization", namespace = "urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")
public class TUtilization {

    @XmlAttribute(name = "Utilization")
    protected String utilization;
    @XmlAttribute(name = "ByDoc")
    protected String byDoc;
    @XmlAttribute(name = "LandUse")
    protected String landUse;

    /**
     * Gets the value of the utilization property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUtilization() {
        return utilization;
    }

    /**
     * Sets the value of the utilization property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUtilization(String value) {
        this.utilization = value;
    }

    /**
     * Gets the value of the byDoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getByDoc() {
        return byDoc;
    }

    /**
     * Sets the value of the byDoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setByDoc(String value) {
        this.byDoc = value;
    }

    /**
     * Gets the value of the landUse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLandUse() {
        return landUse;
    }

    /**
     * Sets the value of the landUse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLandUse(String value) {
        this.landUse = value;
    }

}
